"""Rendering backends for different shader platforms.

This module provides rendering backends that handle the runtime display of
shader code generated by target languages.
"""

from py2glsl.transpiler.render.opengl import (
    StandardOpenGLRenderer,
    ShadertoyOpenGLRenderer,
)