name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.13"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      run: |
        python -m pip install uv

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[dev]"

    - name: Lint with ruff
      run: |
        uv pip install ruff
        ruff check .
        ruff format --check .

    - name: Type check with mypy
      run: |
        mypy py2glsl tests

    - name: Test with pytest
      run: |
        pytest tests/ --cov=py2glsl --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
